config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope '/admin' do
    resources :frases, :plans, :animals, :visita, :instructors
  end
  get 'escuela', to: 'estaticos#escuela'
  get 'visitas', to: 'estaticos#visitas'
  get 'mercado', to: 'estaticos#mercado'
  get 'contacto', to: 'estaticos#contacto'

  root 'estaticos#inicio'

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  validates :nombre, presence: true, length: { minimum: 3}
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:nombre)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= simple_form_for(@instructor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Instructors</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.nombre %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @instructor.nombre %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>