config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope '/admin' do
    resources :frases, :plans, :animals, :visita, :instructors
  end
  get 'escuela', to: 'estaticos#escuela'
  get 'visitas', to: 'estaticos#visitas'
  get 'mercado', to: 'estaticos#mercado'
  get 'contacto', to: 'estaticos#contacto'

  root 'estaticos#inicio'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :archivos, as: :archivable, dependent: :destroy
  accepts_nested_attributes_for :archivos
  validates :nombre, presence: true, length:{ minimum: 3 }
  validates :fecha_nacimiento, presence: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
    @animal.archivos.build
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.archivos.each {|a| a.remove_archivo!}
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:nombre, :descripcion, :fecha_nacimiento, archivos_attributes:[:archivo])
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= simple_form_for(@animal, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
    <%= f.input :fecha_nacimiento %>
    <%= f.simple_fields_for :archivos do |a| %>
      <%= a.input :archivo, as: :file %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Animals</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Fecha nacimiento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.nombre %></td>
        <td><%= animal.descripcion %></td>
        <td><%= animal.fecha_nacimiento %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @animal.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @animal.descripcion %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @animal.fecha_nacimiento %>
</p>

<p>
  <% @animal.archivos.each do |i| %>
    <%= image_tag i.archivo_url %>
  <% end %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>