config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope '/admin' do
    resources :frases, :plans, :animals, :visita, :instructors
  end
  get 'escuela', to: 'estaticos#escuela'
  get 'visitas', to: 'estaticos#visitas'
  get 'mercado', to: 'estaticos#mercado'
  get 'contacto', to: 'estaticos#contacto'

  root 'estaticos#inicio'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates :nombre, presence: true, length: { minimum: 3}
  validates :descripcion, presence: true, length: { minimum: 3}
  validates :precio, presence: true, numericality: true
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:nombre, :descripcion, :precio)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= simple_form_for(@plan) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :descripcion %>
    <%= f.input :precio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plans</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.nombre %></td>
        <td><%= plan.descripcion %></td>
        <td><%= plan.precio %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @plan.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @plan.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @plan.precio %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>