config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope '/admin' do
    resources :frases, :plans, :animals, :visita, :instructors
  end
  get 'escuela', to: 'estaticos#escuela'
  get 'visitas', to: 'estaticos#visitas'
  get 'mercado', to: 'estaticos#mercado'
  get 'contacto', to: 'estaticos#contacto'

  root 'estaticos#inicio'

end

app/views/layouts/_nav_admin.html.erb
<li><%= link_to 'Animales' ,animals_path %></li>
<li><%= link_to 'Instructores' ,instructors_path %></li>
<li><%= link_to 'Planes' ,plans_path %></li>
<li><%= link_to 'Visitas' ,visita_path %></li>
<li><%= link_to 'Desconectar' ,destroy_user_session_path, method: :delete %></li>

app/views/layouts/_nav_usuario.html.erb
<li><%= link_to 'Inicio' ,root_path %></li>
<li><%= link_to 'Escuela' ,escuela_path %></li>
<li><%= link_to 'Visitas' ,visitas_path %></li>
<li><%= link_to 'Mercado' ,mercado_path %></li>
<li><%= link_to 'Contacto' ,contacto_path %></li>

app/views/layouts/_navegacion.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Escuela Internacional de Doma Taurina</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= render 'layouts/nav_usuario' %>
        <%= render 'layouts/nav_admin' if user_signed_in? %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Escuela Internacional de Doma Taurina" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= content_for?(:fondo) ? yield(:fondo) : nil %>
    <header>
      <%= render 'layouts/navegacion' %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>